### PR TITLE
Lime schedulers

### PR DESCRIPTION
**Pull request by SPD3**

### CODE REVIEW

**Comment by SPD3** [comment]
Code is from last year

**Comment by Andromeda1ASRSD** [comment]
i do not want to lose all of this work. there are some bug fixes to the limelight

**Comment by schleprock** [comment]
why are these PR's being closed? i know we need at least a few of them...

bill

**Comment by schleprock** [comment]
I went into the wrong terminal and entered the wrong command. I'm restoring
all the branches now.
~Owen

**Comment by schleprock** [comment]
ok, thank you

**Comment by schleprock** [comment]
while this is an interesting solution to the problem, the architecture of PID loops has changed.

**Pull request closed without merging**
